import "./globals.css";
import "@/app/styles/themes.css";
import styles from "@/app/styles/Layout.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Titlebar from "@/app/components/Titlebar";
import Sidebar from "@/app/components/Sidebar";
import Explorer from "@/app/components/Explorer";
import Tabsbar from "@/app/components/Tabsbar";
import Bottombar from "@/app/components/Boottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  //pageProps: any
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      {/* <Head title={`Sachin Panchal | ${pageProps.title}`} />       */}
      <body className={inter.className}>
        <Titlebar />
        <div className={styles.main}>
          <Sidebar />
          <Explorer />
          <div style={{ width: "100%" }}>
            <Tabsbar />
            <main id="main-editor" className={styles.content}>
              {children}
            </main>
          </div>
        </div>
        <Bottombar />
      </body>
    </html>
  );
};

export default RootLayout;
